/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_inria_genscale_dbscan_impl_plast_RequestResult */

#ifndef _Included_org_inria_genscale_dbscan_impl_plast_RequestResult
#define _Included_org_inria_genscale_dbscan_impl_plast_RequestResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_inria_genscale_dbscan_impl_plast_RequestResult
 * Method:    retrieveNext
 * Signature: (JLorg/inria/genscale/dbscan/api/IObjectFactory;)Lorg/inria/genscale/dbscan/api/IQueryResult;
 */
JNIEXPORT jobject JNICALL Java_org_inria_genscale_dbscan_impl_plast_RequestResult_retrieveNext
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
