/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_inria_genscale_dbscan_impl_plast_RequestManager */

#ifndef _Included_org_inria_genscale_dbscan_impl_plast_RequestManager
#define _Included_org_inria_genscale_dbscan_impl_plast_RequestManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_inria_genscale_dbscan_impl_plast_RequestManager
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_inria_genscale_dbscan_impl_plast_RequestManager_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
