/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_inria_genscale_dbscan_impl_plast_Request */

#ifndef _Included_org_inria_genscale_dbscan_impl_plast_RequestController
#define _Included_org_inria_genscale_dbscan_impl_plast_RequestController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_inria_genscale_dbscan_impl_plast_RequestController
 * Method:    enableLibrary
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_inria_genscale_dbscan_impl_plast_RequestController_enableLibrary
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
