/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_inria_genscale_dbscan_impl_plast_Hit */

#ifndef _Included_org_inria_genscale_dbscan_impl_plast_Hit
#define _Included_org_inria_genscale_dbscan_impl_plast_Hit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_inria_genscale_dbscan_impl_plast_Hit
 * Method:    retrieveNext
 * Signature: (JLorg/inria/genscale/dbscan/api/IObjectFactory;Lorg/inria/genscale/dbscan/api/ISequence;Lorg/inria/genscale/dbscan/api/ISequence;)Lorg/inria/genscale/dbscan/api/IHsp;
 */
JNIEXPORT jobject JNICALL Java_org_inria_genscale_dbscan_impl_plast_Hit_retrieveNext
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
