/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_inria_genscale_dbscan_impl_plast_QueryResult */

#ifndef _Included_org_inria_genscale_dbscan_impl_plast_QueryResult
#define _Included_org_inria_genscale_dbscan_impl_plast_QueryResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_inria_genscale_dbscan_impl_plast_QueryResult
 * Method:    retrieveNext
 * Signature: (JLorg/inria/genscale/dbscan/api/IObjectFactory;)Lorg/inria/genscale/dbscan/api/IHit;
 */
JNIEXPORT jobject JNICALL Java_org_inria_genscale_dbscan_impl_plast_QueryResult_retrieveNext
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
