/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_inria_genscale_dbscan_impl_plast_RequestManager */

#ifndef _Included_org_inria_genscale_dbscan_impl_plast_RequestManager
#define _Included_org_inria_genscale_dbscan_impl_plast_RequestManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_inria_genscale_dbscan_impl_plast_RequestManager
 * Method:    initIDs
 * Signature: (String)V
 */
JNIEXPORT void JNICALL Java_org_inria_genscale_dbscan_impl_plast_RequestManager_initIDs
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_inria_genscale_dbscan_impl_plast_RequestManager
 * Method:    createPeerRequest
 * Signature: (Ljava/util/Properties;)J
 */
JNIEXPORT jlong JNICALL Java_org_inria_genscale_dbscan_impl_plast_RequestManager_createPeerRequest
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
